{% set name = "dmlc" %}
{% set version = "0.6.dev20251006040014" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-core/archive/{{ version }}.tar.gz
  sha256: 116cd430c47798b20010c9030e8b49f32e8de14a7044008e93873cc44c2ddafc

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.14
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - ninja

test:
  commands:
    - test -d ${PREFIX}/include/dmlc   # [unix]

about:
  home: https://github.com/dmlc/dmlc-core
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Distributed Machine Learning Common Codebase
  description: |
    DMLC-Core is the backbone library to support all DMLC projects, offers the bricks to 
    build efficient and scalable distributed machine learning libraries.
  doc_url: https://dmlc-core.readthedocs.io/en/latest/
  dev_url: https://github.com/dmlc/dmlc-core

extra:
  recipe-maintainers:
    - marcelotrevisani
    - hcho3
