{% set name = "dmlc" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-core/archive/v{{ version }}.tar.gz
  sha256: 922ee3ce021b35204f1e424666afa06647f4fc5ce9a920c12e7f850ca2cc2acb

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - openmp
    - curl
    - openssl
    - backtrace
  run:
    - curl
    - backtrace

test:
  commands:
    - test -d ${PREFIX}/include/dmlc   # [unix]

about:
  home: https://github.com/dmlc/dmlc-core
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Distributed Machine Learning Common Codebase
  description: |
    DMLC-Core is the backbone library to support all DMLC projects, offers the bricks to 
    build efficient and scalable distributed machine learning libraries.
  doc_url: https://dmlc-core.readthedocs.io/en/latest/
  dev_url: https://github.com/dmlc/dmlc-core

extra:
  recipe-maintainers:
    - marcelotrevisani
    - hcho3
